name: Kenny from the Block
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73887
title: Kenneth Lim
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76a2d3'
    - '#1e2128'
    - '#4a719c'
    - '#cbddf1'
    - '#fbfdfa'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
